server:
  port: 8090
spring:
  application:
    name: blog-personal
  datasource:
    url: jdbc:mysql://localhost:3306/blog-personal
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
